tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.viewIndex, name='url-index-default'),
    path('select', views.viewSelectYear, name='url-select-year'),
    path('error', views.viewRenderErrorTemplate, name='url-error'),

     ### Authentication - public urls ###
    path('login', views.ViewLogin.as_view(), name='url-login'),
    path('register', views.ViewRegister.as_view(), name='url-register'),
    path('logout', views.ViewLogout.as_view(), name='url-logout'),
    path('register/<str:token>/verify-email/<str:uidb64>', views.view_verfiy_email, 
         name='url-register-email-verify'),
    path('register/<str:token>/verify-forgot-password/<str:uidb64>', views.view_verfiy_email, 
         name='url-forgot-password-verify'),
    path('f_pass/request', views.ViewRequestPasswordChange.as_view(), 
         name='url-forgot-password-request'),
    path('f_pass/<str:identifier>/<str:uidb64>/confirm', views.ViewConfirmPasswordChange.as_view(), 
         name='url-forgot-password-confrim'),
     #####################################

    path('<int:year>', views.viewIndex, name='url-index-year'),
    path('<slug:slug>/edit', views.ViewEditTask.as_view(), name='url-edit-task'),
    path('<slug:slug>/delete', views.ViewDeleteTask.as_view(), name='url-delete-task'),
    path('<int:year>/<str:month>', views.viewShowMonthDates, name='url-month-data'),
    path('<int:year>/<str:month>/<int:date>/data', views.viewShowDateData, name='url-date-data'),
    path('<int:year>/<str:month>/<int:date>/create', views.ViewCreateTask.as_view(), name='url-create-task'),
]



# List of public page urls which unauthenticated user can access
# Custom list, not django specific
PUBLIC_URLS = [
    "url-login",
    "url-register",
    "url-register-email-verify",
    "url-forgot-password-verify",
    "url-forgot-password-request",
    "url-forgot-password-confrim",
    "url-error",
]

timezup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks')),
]

tasks/models.py
# Create your models here.

from .models import Year, Month, Date, CombineDate, Task, CustomUser

tasks/models/combine_date.py
from django.db import models
from tasks.models.separate_dates import Date, Month, Year

class CombineDate(models.Model):
    date = models.ForeignKey(Date, on_delete=models.PROTECT, null=False)
    month = models.ForeignKey(Month, on_delete=models.PROTECT, null=False)
    year = models.ForeignKey(Year, on_delete=models.PROTECT, null=False)

    def __str__(self):
        return f"{self.month.data.title()} {self.date.data}, {self.year.data}"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["date", "month", "year"], 
                name="unique_dates", 
                violation_error_message="Combination of Date already exist")
        ]
        verbose_name = "Date of the Task"

tasks/forms/login_form.py
from django import forms
from django.conf import settings
import re
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    username_or_email = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={"placeholder": "Username or E-mail"}),
        error_messages={
            "required": "Username or Email field cannot be empty.",
            "max_length": "Maximum of 254 characters allowed in username or email field."
        })
    password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput(attrs={"placeholder": "Password", "show": "*"}),
        error_messages={
            "required": "Password field cannot be empty.",
            "max_length": "Maximum of 128 characters allowed in password field."
        })
    
    def clean_username_or_email(self):
        value = self.cleaned_data.get("username_or_email")
        if re.fullmatch(settings.USERNAME_REGEX, value):
            username = value
        elif re.fullmatch(settings.EMAIL_REGEX, value):
            try:
                user = get_user_model().objects.get(email=value)
                username = user.username
            except Exception:
                raise forms.ValidationError("No account linked to given email address.", code="invalid")
        else:
            raise forms.ValidationError("Given username or email is in invalid format.", code="invalid")
        return username

tasks/forms/password_change_confirm_form.py
from django import forms
from django.contrib.auth import get_user_model
from tasks.forms.register_form import validate_password

class PasswordChangeConfirmForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=128,
        widget=forms.TextInput(attrs={"placeholder": "Confirm Password", "autocomplete": "off"})
        )

    # Validate Password
    def clean_password(self):
        return validate_password(self, "password")

    # Validate Confirm Password
    def clean_confirm_password(self):
        return validate_password(self, "confirm_password")
    
    class Meta:
        model = get_user_model()
        fields = ["password", "confirm_password"]
        error_messages = {
            "password": {
                "required": "Password Field is mandatory",
                "max_length": "Maximum 128 characters allowed"
            },
            "confirm_password": {
                "required": "Confirm Password Field is mandatory",
                "max_length": "Maximum 128 characters allowed"
            }
        }
        widgets ={
            "password": forms.PasswordInput(attrs={"placeholder": "Password"})
        }

tasks/forms/password_change_request_form.py
from django import forms
from django.contrib.auth import get_user_model
from django.conf import settings
import re


class PasswordChangeRequestForm(forms.Form):
    username_or_email = forms.CharField(max_length=254, label="Username or E-mail", 
        error_messages={
            "required": "Email Field is mandatory",
            "max_length": "Maximum 254 characters allowed",
            "invalid": "Invalid email input, must follow example@domain.com",
            },
        widget=forms.TextInput(attrs={"placeholder": "Username or Password"})
        )

    def clean_username_or_email(self):
        value = self.cleaned_data.get("username_or_email")

        if re.fullmatch(settings.EMAIL_REGEX, value):
            if not get_user_model().objects.filter(email=value).exists():
                raise forms.ValidationError("No account asssociated with given email address found.", 
                    code="invalid")
        elif re.fullmatch(settings.USERNAME_REGEX, value):
            if not get_user_model().objects.filter(username=value).exists():
                raise forms.ValidationError("No account asssociated with given username found.",
                    code="invalid")
        else:
            raise forms.ValidationError("Invalid email or username format", code="invalid")
        
        return value

tasks/forms/task_form.py
from django import forms
from tasks.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["task"]
        labels = {
            "task": "Enter Task"
        }
        widgets = {
            "task": forms.Textarea(
                attrs={
                    "class": "txtinpt",
                    "id": "task",
                    "cols": 30,
                    "rows": 10
                    }
                )
        }
        error_messages = {
            "task": {
                "required": "Task Field is mandatory",
                "max_length": "Maximum 255 characters allowed"
            }
        }

tasks/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import View
from django.contrib.auth.views import LogoutView
from django.contrib.auth import get_user_model, authenticate, login
from django.conf import settings
from django.db.models import Q
from .models import CombineDate, Task, Year, Month, Date
from .forms import TaskForm, LoginForm, RegisterForm, PasswordChangeRequestForm, PasswordChangeConfirmForm
from .helper_methods import *
import datetime


# return error template
def viewRenderErrorTemplate(request):
    """
    Return error template as response
    Args: 
        request (django.http.request.HttpRequest)
    Returns:
        HttpResponse: an http response instance from render()
    """
    context = dict()
    context["app_name"] = settings.PROJECT_APPLICATION_NAME
    return render(request, "tasks/error.html", context)


# Index first page , months rendering
def viewIndex(request, year=None):
    year = validateYear(year)
    months_data = Month.objects.all()

    context = {
        'year': year,
        'months_data': months_data,
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'username': request.user.username,
        'is_staff': request.user.is_staff

    }
    return render(request, 'tasks/index.html', context)


# Select year
def viewSelectYear(request):
    current_year = int(datetime.datetime.now().strftime('%Y'))
    context = {
        'current_year': current_year,
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'username': request.user.username,
        'is_staff': request.user.is_staff
    }
    return render(request, 'tasks/years.html', context)


# Month wise dates rendering
def viewShowMonthDates(request, year, month):
    
    year = validateYear(year)
    month = validateMonth(month)
    end = get_month_end_date(month["number"], year)

    context = {
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'year': year,
        'month_name': month["name"],
        'end_date': end,
        'username': request.user.username,
        'is_staff': request.user.is_staff
    }
    return render(request, 'tasks/month_dates.html', context)


# Date wise data show
def viewShowDateData(request, year, month, date):
    year = validateYear(year)
    month = validateMonth(month)
    date = validateDate(date, month['number'], year)
    
    year_inst = Year.objects.get(data=year)
    month_inst = Month.objects.get(pk=month["number"])
    date_inst = Date.objects.get(data=date)

    # since get_or_create return (object, created)
    combine_date, _ = CombineDate.objects.get_or_create(year=year_inst, month=month_inst, date=date_inst)
    tasks = Task.objects.filter(combine_date=combine_date, user=request.user)
    context = {
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'year': year,
        'month': month["name"],
        'date': date,
        'tasks': tasks,
        'username': request.user.username,
        'is_staff': request.user.is_staff
    }

    return render(request, 'tasks/dates.html', context)


# Class based view for new Task Creation
# Replacing CreateView with FormView works same 
class ViewCreateTask(CreateView):
    template_name = "tasks/form.html"
    model = Task
    form_class = TaskForm
    success_mssg_ = ["Task successfully added"] # This is custom property
    # in context "form" already pass to form.html
    # If we want additional override with get_context_data

    # Ensuring date, month and year is valid
    def get(self, request, *args, **kwargs):
        year = validateYear(kwargs["year"])
        month = validateMonth(kwargs["month"])
        validateDate(kwargs["date"], month['number'], year)
        self.kwargs["month"] = month["name"] # if month no. in url then proceed with name 
        return super().get(request, *args, **kwargs)

    # Setting context for template rendering
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["date"] = self.kwargs["date"]
        context["month"] = self.kwargs["month"]
        context["year"] = self.kwargs["year"]
        context["app_name"] = settings.PROJECT_APPLICATION_NAME
        context["username"] = self.request.user.username
        context["is_staff"] = self.request.user.is_staff
        context["title"] = "Create Task"
        context["messages"] = self.success_mssg_
        context["show_message"] = False
        context["is_error"] = False
        context["submit_url"] = reverse_lazy("tasks:url-create-task", kwargs={
            "date": self.kwargs["date"],
            "month": self.kwargs["month"],
            "year": self.kwargs["year"]
            })
        month_no = int(validateMonth(self.kwargs["month"])["number"])
        requested_date = datetime.datetime(int(context["year"]), month_no, int(context["date"])).date()
        current_date = datetime.datetime.now().date()
        print(requested_date)
        print(current_date)
        if requested_date < current_date:
            context["form_not_accepted"] = True
        else:
            context["form_not_accepted"] = False
        return context
    
    # This method called when a valid form is submitted
    def form_valid(self, form):
        try:
            context = self.get_context_data()
            date = Date.objects.get(data=self.kwargs["date"])
            month = Month.objects.get(data=self.kwargs["month"])
            year = Year.objects.get(data=self.kwargs["year"])
            # get_or_create return tuple (object, boolean), boolean tell either new obj craeted or not
            combine_date, _ = CombineDate.objects.get_or_create(date=date, month=month, year=year)

            new_task = Task(task=form.cleaned_data["task"], combine_date=combine_date, 
                user=self.request.user)
            new_task.save()
            context["show_message"] = True # Show message
            context["is_error"] = False # There are no errors
            context["messages"] = self.success_mssg_
            return render(self.request, self.template_name, context)
        except Exception as e:
            print("Develoment Error: Creating Task :", e)
            # If Unique Constraint fail for duplicate entry on same date
            if "unique_task_date" in str(e):
                form.errors["custom_error"] = ["Task already exist for this date"]
                return self.form_invalid(form)
            else:
                form.errors["custom_error"] = ["Something went wrong, please try again later"]
                return self.form_invalid(form)
        
    # This method is called when a invalid form is submitted
    def form_invalid(self, form):
        context = self.get_context_data()
        context["show_message"] = True # Show message
        context["is_error"] = True # There are errors
        context["messages"] = [error for field_errors in form.errors.values()
                                for error in field_errors] # Flattening Dict of fields(keys): errors (list) 
        return render(self.request, self.template_name, context)
    

# Class based view for updation of Task
class ViewEditTask(UpdateView):
    template_name = "tasks/form.html"
    model = Task
    form_class = TaskForm
    success_mssg_ = ["Task modified successfully"]
    # in context "form" already pass to form.html
    # If we want additional override with get_context_data

    # Setting context for template rendering
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        combined_date = self.get_object().combine_date
        context["date"] = combined_date.date.data
        context["month"] = combined_date.month.data
        context["year"] = combined_date.year.data
        context["app_name"] = settings.PROJECT_APPLICATION_NAME
        context["username"] = self.request.user.username
        context["is_staff"] = self.request.user.is_staff
        context["title"] = "Edit Task"
        context["messages"] = self.success_mssg_
        context["show_message"] = False
        context["is_error"] = False
        context["submit_url"] = reverse_lazy("tasks:url-edit-task", kwargs={
            "slug": self.kwargs["slug"]
        })
        month_no = int(validateMonth(context["month"])["number"])
        requested_date = datetime.datetime(int(context["year"]), month_no, int(context["date"])).date()
        current_date = datetime.datetime.now().date()
        if requested_date < current_date:
            context["form_not_accepted"] = True
        else:
            context["form_not_accepted"] = False
        return context
    
    # This method called when a valid form is submitted
    def form_valid(self, form):
        context = self.get_context_data()
        try:
            task = self.get_object()
            if task.task == form.cleaned_data["task"]:
                form.errors["custom_error"] = ["Nothing to update."]
                return self.form_invalid(form)   
            task.task = form.cleaned_data["task"]
            task.save()
            context["show_message"] = True # Show message
            context["is_error"] = False # There are no errors
            context["messages"] = self.success_mssg_
            return render(self.request, self.template_name, context)
        except Exception as e:
            # If Unique Constraint fail for duplicate entry on same date
            if "unique_task_date" in str(e):
                form.errors["custom_error"] = ["Task already exist for this date"]
                return self.form_invalid(form)
            else:
                form.errors["custom_error"] = ["Something went wrong, please try again later"]
                return self.form_invalid(form)
        
    # This method is called when a invalid form is submitted
    def form_invalid(self, form):

tasks/templates/tasks/authenticate/forgot_password_confirm.html
{% extends 'tasks/index.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'tasks/authenticate/css/auth.css' %}">
{% endblock style %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_style %}
{% endblock profile_style %}

{% block profile %}
{% endblock profile %}

{% block body %}
    {% if disable %}
        <h3 class="{% if error %}error{% else %}success{% endif %} h3_error">{{ disable_message }}</h3>
    {% else %}
        <form class="form" method="POST" action="{{ submit_url }}">
            {% csrf_token %}
            <h2>Change Password</h2>
            {{ form.password }}
            {{ form.confirm_password }}
            <button type="submit">Submit</button>
        </form>
    {% endif %}

    {% if form.errors %}
        <ul>
            {% for field_error_dict in form.errors.values %}
                {% for error_data in field_error_dict %}
                    <li class="{% if error %}error{% else %}success{% endif %}">{{ error_data }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <div class="links">
        <a href="{% url 'tasks:url-login' %}">
            <button class="links_button">Login</button>
        </a>
        <a href="{% url 'tasks:url-register' %}">
            <button  class="links_button">Register</button>
        </a>
    </div>
{% endblock body %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_script %}
{% endblock profile_script %}

tasks/templates/tasks/authenticate/forgot_password_request.html
{% extends 'tasks/index.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'tasks/authenticate/css/auth.css' %}">
{% endblock style %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_style %}
{% endblock profile_style %}

{% block profile %}
{% endblock profile %}

{% block body %}
    <form class="form" method="POST" action="{% url 'tasks:url-forgot-password-request' %}">
        {% csrf_token %}
        <h2>Forgot Password</h2>
        <p>Enter email or username for password reset link.</p>
        {{ form.username_or_email }}
        <button type="submit">Reset Password</button>
    </form>

    {% if form.errors %}
        <ul>
            {% for field_error_dict in form.errors.values %}
                {% for error_data in field_error_dict %}
                    <li class="{% if error %}error{% else %}success{% endif %}">{{ error_data }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <div class="links">
        <a href="{% url 'tasks:url-login' %}">
            <button class="links_button">Login</button>
        </a>
        <a href="{% url 'tasks:url-register' %}">
            <button  class="links_button">Register</button>
        </a>
    </div>
{% endblock body %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_script %}
{% endblock profile_script %}

tasks/templates/tasks/authenticate/login.html
{% extends 'tasks/index.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'tasks/authenticate/css/auth.css' %}">
{% endblock style %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_style %}
{% endblock profile_style %}

{% block profile %}
{% endblock profile %}

{% block body %}
    <form class="form" method="POST" action="{% url "tasks:url-login" %}">
        {% csrf_token %}
        <h2>Login</h2>
        {{ form.username_or_email }}

        <div class="password-input">
            {{ form.password }}
            <button toggle="#id_password" class="eye-toggle" type="button">
                <img id="open_eye" src="{% static 'tasks/authenticate/images/open_eye.png' %}" alt="Show">
                <img id="close_eye" src="{% static 'tasks/authenticate/images/close_eye.png' %}" alt="Hide">
            </button>
          </div>
        <button type="submit">Login</button>
    </form>

    {% if form.errors %}
        <ul>
            {% for field_error_dict in form.errors.values %}
                {% for error_data in field_error_dict %}
                    <li class="{% if error %}error{% else %}success{% endif %}">{{ error_data }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}
    
    <div class="links">
        <a href="{% url 'tasks:url-register' %}">
            <button class="links_button">Create Account</button>
        </a>
        <a href="{% url 'tasks:url-forgot-password-request' %}">
            <button  class="links_button">Forgot Password?</button>
        </a>
    </div>

    <script type="text/javascript" src="{% static 'tasks/authenticate/js/auth.js' %}"></script>
{% endblock body %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_script %}
{% endblock profile_script %}

tasks/templates/tasks/authenticate/register.html
{% extends 'tasks/index.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'tasks/authenticate/css/auth.css' %}">
{% endblock style %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_style %}
{% endblock profile_style %}

{% block profile %}
{% endblock profile %}

{% block body %}
    <form class="form" method="POST" action="{% url "tasks:url-register" %}">
        {% csrf_token %}
        <h2>Register</h2>
        {{ form.username }}
        {{ form.email }}
        {{ form.password }}
        {{ form.confirm_password }}
        <button type="submit">Register</button>
    </form>
    
    {% if form.errors %}
        <ul>
            {% for field_error_dict in form.errors.values %}
                {% for error_data in field_error_dict %}
                    <li class="{% if error %}error{% else %}success{% endif %}">{{ error_data }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <div class="links">
        <a href="{% url 'tasks:url-login' %}">
            <button class="links_button">Login</button>
        </a>
        <a href="{% url 'tasks:url-forgot-password-request' %}">
            <button class="links_button">Forgot Password</button>
        </a>
    </div>
{% endblock body %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_script %}
{% endblock profile_script %}

tasks/templates/tasks/authenticate/verification_successful.html
{% extends 'tasks/index.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'tasks/authenticate/css/verification_successful.css' %}">
{% endblock style %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_style %}
{% endblock profile_style %}

{% block profile %}
{% endblock profile %}

{% block body_title %}
    <h1>{{ app_name }}</h1>
    <h3 class="{% if fail %}error{% else %}success{% endif %}">{{ label_message }}</h3>
{% endblock body_title %}

{% block body %}    
    <a href="{{ button_url }}"><button>{{ button_message }}</button></a>
{% endblock body %}

{% comment %} Because we don't want profile section in public pages {% endcomment %}
{% block profile_script %}
{% endblock profile_script %}