tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.viewIndex, name='url-index-default'),
    path('select', views.viewSelectYear, name='url-select-year'),
    path('error', views.viewRenderErrorTemplate, name='url-error'),

     ### Authentication - public urls ###
    path('login', views.ViewLogin.as_view(), name='url-login'),
    path('register', views.ViewRegister.as_view(), name='url-register'),
    path('logout', views.ViewLogout.as_view(), name='url-logout'),
    path('register/<str:token>/verify-email/<str:uidb64>', views.view_verfiy_email, 
         name='url-register-email-verify'),
    path('register/<str:token>/verify-forgot-password/<str:uidb64>', views.view_verfiy_email, 
         name='url-forgot-password-verify'),
    path('f_pass/request', views.ViewRequestPasswordChange.as_view(), 
         name='url-forgot-password-request'),
    path('f_pass/<str:identifier>/<str:uidb64>/confirm', views.ViewConfirmPasswordChange.as_view(), 
         name='url-forgot-password-confrim'),
     #####################################

    path('<int:year>', views.viewIndex, name='url-index-year'),
    path('<slug:slug>/edit', views.ViewEditTask.as_view(), name='url-edit-task'),
    path('<slug:slug>/delete', views.ViewDeleteTask.as_view(), name='url-delete-task'),
    path('<int:year>/<str:month>', views.viewShowMonthDates, name='url-month-data'),
    path('<int:year>/<str:month>/<int:date>/data', views.viewShowDateData, name='url-date-data'),
    path('<int:year>/<str:month>/<int:date>/create', views.ViewCreateTask.as_view(), name='url-create-task'),
]



# List of public page urls which unauthenticated user can access
# Custom list, not django specific
PUBLIC_URLS = [
    "url-login",
    "url-register",
    "url-register-email-verify",
    "url-forgot-password-verify",
    "url-forgot-password-request",
    "url-forgot-password-confrim",
    "url-error",
]

timezup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks')),
]

tasks/models.py
# Create your models here.

from .models import Year, Month, Date, CombineDate, Task, CustomUser

tasks/models/combine_date.py
from django.db import models
from tasks.models.separate_dates import Date, Month, Year

class CombineDate(models.Model):
    date = models.ForeignKey(Date, on_delete=models.PROTECT, null=False)
    month = models.ForeignKey(Month, on_delete=models.PROTECT, null=False)
    year = models.ForeignKey(Year, on_delete=models.PROTECT, null=False)

    def __str__(self):
        return f"{self.month.data.title()} {self.date.data}, {self.year.data}"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["date", "month", "year"], 
                name="unique_dates", 
                violation_error_message="Combination of Date already exist")
        ]
        verbose_name = "Date of the Task"

tasks/forms/login_form.py
from django import forms
from django.conf import settings
import re
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    username_or_email = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={"placeholder": "Username or E-mail"}),
        error_messages={
            "required": "Username or Email field cannot be empty.",
            "max_length": "Maximum of 254 characters allowed in username or email field."
        })
    password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput(attrs={"placeholder": "Password", "show": "*"}),
        error_messages={
            "required": "Password field cannot be empty.",
            "max_length": "Maximum of 128 characters allowed in password field."
        })
    
    def clean_username_or_email(self):
        value = self.cleaned_data.get("username_or_email")
        if re.fullmatch(settings.USERNAME_REGEX, value):
            username = value
        elif re.fullmatch(settings.EMAIL_REGEX, value):
            try:
                user = get_user_model().objects.get(email=value)
                username = user.username
            except Exception:
                raise forms.ValidationError("No account linked to given email address.", code="invalid")
        else:
            raise forms.ValidationError("Given username or email is in invalid format.", code="invalid")
        return username

tasks/forms/password_change_confirm_form.py
from django import forms
from django.contrib.auth import get_user_model
from tasks.forms.register_form import validate_password

class PasswordChangeConfirmForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=128,
        widget=forms.TextInput(attrs={"placeholder": "Confirm Password", "autocomplete": "off"})
        )

    # Validate Password
    def clean_password(self):
        return validate_password(self, "password")

    # Validate Confirm Password
    def clean_confirm_password(self):
        return validate_password(self, "confirm_password")
    
    class Meta:
        model = get_user_model()
        fields = ["password", "confirm_password"]
        error_messages = {
            "password": {
                "required": "Password Field is mandatory",
                "max_length": "Maximum 128 characters allowed"
            },
            "confirm_password": {
                "required": "Confirm Password Field is mandatory",
                "max_length": "Maximum 128 characters allowed"
            }
        }
        widgets ={
            "password": forms.PasswordInput(attrs={"placeholder": "Password"})
        }

tasks/forms/password_change_request_form.py
from django import forms
from django.contrib.auth import get_user_model
from django.conf import settings
import re


class PasswordChangeRequestForm(forms.Form):
    username_or_email = forms.CharField(max_length=254, label="Username or E-mail", 
        error_messages={
            "required": "Email Field is mandatory",
            "max_length": "Maximum 254 characters allowed",
            "invalid": "Invalid email input, must follow example@domain.com",
            },
        widget=forms.TextInput(attrs={"placeholder": "Username or Password"})
        )

    def clean_username_or_email(self):
        value = self.cleaned_data.get("username_or_email")

        if re.fullmatch(settings.EMAIL_REGEX, value):
            if not get_user_model().objects.filter(email=value).exists():
                raise forms.ValidationError("No account asssociated with given email address found.", 
                    code="invalid")
        elif re.fullmatch(settings.USERNAME_REGEX, value):
            if not get_user_model().objects.filter(username=value).exists():
                raise forms.ValidationError("No account asssociated with given username found.",
                    code="invalid")
        else:
            raise forms.ValidationError("Invalid email or username format", code="invalid")
        
        return value

tasks/forms/task_form.py
from django import forms
from tasks.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["task"]
        labels = {
            "task": "Enter Task"
        }
        widgets = {
            "task": forms.Textarea(
                attrs={
                    "class": "txtinpt",
                    "id": "task",
                    "cols": 30,
                    "rows": 10
                    }
                )
        }
        error_messages = {
            "task": {
                "required": "Task Field is mandatory",
                "max_length": "Maximum 255 characters allowed"
            }
        }

tasks/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import View
from django.contrib.auth.views import LogoutView
from django.contrib.auth import get_user_model, authenticate, login
from django.conf import settings
from django.db.models import Q
from .models import CombineDate, Task, Year, Month, Date
from .forms import TaskForm, LoginForm, RegisterForm, PasswordChangeRequestForm, PasswordChangeConfirmForm
from .helper_methods import *
import datetime


# return error template
def viewRenderErrorTemplate(request):
    """
    Return error template as response
    Args: 
        request (django.http.request.HttpRequest)
    Returns:
        HttpResponse: an http response instance from render()
    """
    context = dict()
    context["app_name"] = settings.PROJECT_APPLICATION_NAME
    return render(request, "tasks/error.html", context)


# Index first page , months rendering
def viewIndex(request, year=None):
    year = validateYear(year)
    months_data = Month.objects.all()

    context = {
        'year': year,
        'months_data': months_data,
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'username': request.user.username,
        'is_staff': request.user.is_staff

    }
    return render(request, 'tasks/index.html', context)


# Select year
def viewSelectYear(request):
    current_year = int(datetime.datetime.now().strftime('%Y'))
    context = {
        'current_year': current_year,
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'username': request.user.username,
        'is_staff': request.user.is_staff
    }
    return render(request, 'tasks/years.html', context)


# Month wise dates rendering
def viewShowMonthDates(request, year, month):
    
    year = validateYear(year)
    month = validateMonth(month)
    end = get_month_end_date(month["number"], year)

    context = {
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'year': year,
        'month_name': month["name"],
        'end_date': end,
        'username': request.user.username,
        'is_staff': request.user.is_staff
    }
    return render(request, 'tasks/month_dates.html', context)


# Date wise data show
def viewShowDateData(request, year, month, date):
    year = validateYear(year)
    month = validateMonth(month)
    date = validateDate(date, month['number'], year)
    
    year_inst = Year.objects.get(data=year)
    month_inst = Month.objects.get(pk=month["number"])
    date_inst = Date.objects.get(data=date)

    # since get_or_create return (object, created)
    combine_date, _ = CombineDate.objects.get_or_create(year=year_inst, month=month_inst, date=date_inst)
    tasks = Task.objects.filter(combine_date=combine_date, user=request.user)
    context = {
        'app_name': settings.PROJECT_APPLICATION_NAME,
        'year': year,
        'month': month["name"],
        'date': date,
        'tasks': tasks,
        'username': request.user.username,
        'is_staff': request.user.is_staff
    }

    return render(request, 'tasks/dates.html', context)


# Class based view for new Task Creation
# Replacing CreateView with FormView works same 
class ViewCreateTask(CreateView):
    template_name = "tasks/form.html"
    model = Task
    form_class = TaskForm
    success_mssg_ = ["Task successfully added"] # This is custom property
    # in context "form" already pass to form.html
    # If we want additional override with get_context_data

    # Ensuring date, month and year is valid
    def get(self, request, *args, **kwargs):
        year = validateYear(kwargs["year"])
        month = validateMonth(kwargs["month"])
        validateDate(kwargs["date"], month['number'], year)
        self.kwargs["month"] = month["name"] # if month no. in url then proceed with name 
        return super().get(request, *args, **kwargs)

    # Setting context for template rendering
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["date"] = self.kwargs["date"]
        context["month"] = self.kwargs["month"]
        context["year"] = self.kwargs["year"]
        context["app_name"] = settings.PROJECT_APPLICATION_NAME
        context["username"] = self.request.user.username
        context["is_staff"] = self.request.user.is_staff
        context["title"] = "Create Task"
        context["messages"] = self.success_mssg_
        context["show_message"] = False
        context["is_error"] = False
        context["submit_url"] = reverse_lazy("tasks:url-create-task", kwargs={
            "date": self.kwargs["date"],
            "month": self.kwargs["month"],
            "year": self.kwargs["year"]
            })
        month_no = int(validateMonth(self.kwargs["month"])["number"])
        requested_date = datetime.datetime(int(context["year"]), month_no, int(context["date"])).date()
        current_date = datetime.datetime.now().date()
        print(requested_date)
        print(current_date)
        if requested_date < current_date:
            context["form_not_accepted"] = True
        else:
            context["form_not_accepted"] = False
        return context
    
    # This method called when a valid form is submitted
    def form_valid(self, form):
        try:
            context = self.get_context_data()
            date = Date.objects.get(data=self.kwargs["date"])
            month = Month.objects.get(data=self.kwargs["month"])
            year = Year.objects.get(data=self.kwargs["year"])
            # get_or_create return tuple (object, boolean), boolean tell either new obj craeted or not
            combine_date, _ = CombineDate.objects.get_or_create(date=date, month=month, year=year)

            new_task = Task(task=form.cleaned_data["task"], combine_date=combine_date, 
                user=self.request.user)
            new_task.save()
            context["show_message"] = True # Show message
            context["is_error"] = False # There are no errors
            context["messages"] = self.success_mssg_
            return render(self.request, self.template_name, context)
        except Exception as e:
            print("Develoment Error: Creating Task :", e)
            # If Unique Constraint fail for duplicate entry on same date
            if "unique_task_date" in str(e):
                form.errors["custom_error"] = ["Task already exist for this date"]
                return self.form_invalid(form)
            else:
                form.errors["custom_error"] = ["Something went wrong, please try again later"]
                return self.form_invalid(form)
        
    # This method is called when a invalid form is submitted
    def form_invalid(self, form):
        context = self.get_context_data()
        context["show_message"] = True # Show message
        context["is_error"] = True # There are errors
        context["messages"] = [error for field_errors in form.errors.values()
                                for error in field_errors] # Flattening Dict of fields(keys): errors (list) 
        return render(self.request, self.template_name, context)
    

# Class based view for updation of Task
class ViewEditTask(UpdateView):
    template_name = "tasks/form.html"
    model = Task
    form_class = TaskForm
    success_mssg_ = ["Task modified successfully"]
    # in context "form" already pass to form.html
    # If we want additional override with get_context_data

    # Setting context for template rendering
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        combined_date = self.get_object().combine_date
        context["date"] = combined_date.date.data
        context["month"] = combined_date.month.data
        context["year"] = combined_date.year.data
        context["app_name"] = settings.PROJECT_APPLICATION_NAME
        context["username"] = self.request.user.username
        context["is_staff"] = self.request.user.is_staff
        context["title"] = "Edit Task"
        context["messages"] = self.success_mssg_
        context["show_message"] = False
        context["is_error"] = False
        context["submit_url"] = reverse_lazy("tasks:url-edit-task", kwargs={
            "slug": self.kwargs["slug"]
        })
        month_no = int(validateMonth(context["month"])["number"])
        requested_date = datetime.datetime(int(context["year"]), month_no, int(context["date"])).date()
        current_date = datetime.datetime.now().date()
        if requested_date < current_date:
            context["form_not_accepted"] = True
        else:
            context["form_not_accepted"] = False
        return context
    
    # This method called when a valid form is submitted
    def form_valid(self, form):
        context = self.get_context_data()
        try:
            task = self.get_object()
            if task.task == form.cleaned_data["task"]:
                form.errors["custom_error"] = ["Nothing to update."]
                return self.form_invalid(form)   
            task.task = form.cleaned_data["task"]
            task.save()
            context["show_message"] = True # Show message
            context["is_error"] = False # There are no errors
            context["messages"] = self.success_mssg_
            return render(self.request, self.template_name, context)
        except Exception as e:
            # If Unique Constraint fail for duplicate entry on same date
            if "unique_task_date" in str(e):
                form.errors["custom_error"] = ["Task already exist for this date"]
                return self.form_invalid(form)
            else:
                form.errors["custom_error"] = ["Something went wrong, please try again later"]
                return self.form_invalid(form)
        
    # This method is called when a invalid form is submitted
    def form_invalid(self, form):

tasks/templates/tasks/dates.html
{% extends 'tasks/index.html' %}
{% load static %}
{% load tasks_tag %}
    
    {% block style %}
        <link rel="stylesheet" href="{% static 'tasks/css/dates.css' %}" type="text/css">
    {% endblock style %}

        {% block body_title %}
            <h1 class="header">
                <a href="{% url 'tasks:url-month-data' year month %}" class="title_a">
                    <span class="centered_content">{{ month | title }} {{ date }}, {{ year }}</span>
                </a>
                <a id="add_image" href="{% url 'tasks:url-create-task' year month date %}">
                    <img src="{% static 'tasks/images/add_button.png' %}" alt="Create New">
                </a>
            </h1>
        {% endblock body_title %}

        {% block body %}
            <div class="page_container">
                {% if  tasks|length > 0 %}
                    {% for counter, task in tasks|enumerate:1 %}
                        <div id="{{ counter }}" class='page' onclick="expandPage(event, '{{ task.task }}')">
                            <div class='page_content'> 
                                {{ task.task }}
                            </div>
                            <div class='page_no'> {{ counter }} </div>
                            <div class="page_operation" 
                                data-code-edit="{% url 'tasks:url-edit-task' slug=task.slug %}" 
                                data-code-delete="{% url 'tasks:url-delete-task' slug=task.slug %}">
                                <button class='btn edit_btn' onclick="editButton(event)">
                                    Edit
                                </button>
                                <button class='btn delete_btn' onclick="deleteButton(event)">
                                    Delete
                                </button>
                            </div>
                            <div class="page_date"> {{ task.created_at|date:"M d, Y - h:i A" }} </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h2 class="no_record"> No Records.... </h2>
                {% endif %}
            </div>
            <script type='text/javascript' src="{% static 'tasks/js/dates.js' %}"></script>
        {% endblock body %}

tasks/templates/tasks/error.html
{% extends 'tasks/index.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'tasks/css/error.css' %}">
{% endblock style %}

{% block body_title %}
{% endblock body_title %}

{% block body %}
    <div class="error-container">
        <div class="error-code">
            <a href="{% url 'tasks:url-index-default' %}">
                <h1>{{ app_name }} &#x1F604;</h1> 
            </a>
        </div>
        <div class="error-code"><img src="{% static 'tasks/images/error.avif' %}" width="175" height="200"></div>
        <div class="error-message">Oops! Something went wrong.</div>
        <p>Sorry, the page you are looking for might have been removed or is temporarily unavailable.</p>
        <a class="back-home" href="{% url 'tasks:url-index-default' %}">Back to Home</a>
    </div>
{% endblock body %}

tasks/templates/tasks/form.html
{% extends 'tasks/index.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'tasks/css/form.css' %}">
{% endblock style %}

{% block body_title %}
    <div class="head">
        <a href="{% url 'tasks:url-index-default' %}">
            <h1>{{ app_name }} &#x1F604;</h1> 
        </a>
        <h2> 
            {{ title }} - 
            <a href="{% url 'tasks:url-date-data' year month date %}"> 
                {{ month|title }} {{ date }}, {{ year }} 
            </a> 
        </h2>
    </div>
{% endblock body_title %}

{% block body %}
<div class="form">
    {% if form_not_accepted %}
        <h3 style="color:yellow;">Warning: Adding or modifying tasks of past is not supported. </h3>
    {% else %}
        <form method="POST" action="{{ submit_url }}">
            {% csrf_token %}
            <label for="{{ form.task.id_for_label }}" class="lbl">{{ form.task.label }}:</label>

            {{ form.task }}
            <input type="submit" class='btn' name='submit_button'>
        </form>
    {% endif %}
</div>
{% if show_message %}
    <div class="message{% if is_error %} error {% endif %}">
        {% for element in messages %}
            <li> {{ element }} </li>
        {% endfor %}
    </div>
{% endif %}
{% endblock body %}

tasks/templates/tasks/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/x-icon" href="{% static 'tasks/images/favicon.ico' %}">
        {% block style %}
            <link rel="stylesheet" href="{% static 'tasks/css/index.css' %}" type="text/css">
        {% endblock style %}
        {% block profile_style %}
            <link rel="stylesheet" href="{% static 'tasks/css/logout.css' %}" type="text/css">
        {% endblock profile_style %}
        <title>{{ app_name }}</title>
    </head>
    <body>
        {% block profile %}
            <div class="profile">
                <button class="show_button" type="button">Show Profile</button>
                <span class="profile_content" style="display:none;">
                    <p class="profile_username">{{ username }}</p>
                    <form class="logout_form" method="POST" action="{% url 'tasks:url-logout' %}">
                        {% csrf_token %}
                        <button id="profile_logout" type="button">Logout</button>
                        {% if is_staff %}<button id="profile_admin" type="button">Admin Panel</button>{% endif %}
                    </form>
                </span>
            </div>
        {% endblock profile %}
        <div class="body_wrapper">
            {% block body_title %}
                <a href="{% url 'tasks:url-index-default' %}" class="title_a">
                    <h1>{{ app_name }} &#x1F604;</h1>
                </a>
                <h2>{{ year }}</h2>
            {% endblock body_title %}
            {% block body %}
            <div class='month_container'>
                {% for month in months_data %}
                    <a href="{% url 'tasks:url-month-data' year month.data %}">
                        <div class='month_items'>{{ month.data|title }}</div>
                    </a>
                {% endfor %}
                <a class='select' href="{% url 'tasks:url-select-year' %}">
                    <div class='month_items year_select'> Select Year </div>
                </a>
            </div>
            {% endblock body %}
        </div>

        {% block profile_script %}
            <script src="{% static 'tasks/js/logout.js' %}" type="text/javascript"></script>
        {% endblock profile_script %}
    </body>
</html>

tasks/templates/tasks/month_dates.html
{% extends 'tasks/index.html' %}
{% load tasks_tag %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type='text/css' href="{% static 'tasks/css/month_dates.css' %}">
{% endblock style %}

{% block body_title %}
    <a class='title_a' href="{% url 'tasks:url-index-year' year%}">
        <h1> {{ month_name|title }}, {{ year }} </h1>
    </a>
{% endblock body_title %}

{% block body %}
    <div class='dates_container'>
        {% with end_date|add:1 as end %}
            {% for date in 1|range:end %}
                <a href="{% url 'tasks:url-date-data' year month_name date %}"> <div class='dates'> {{ date }} </div> </a>
            {% endfor %}
        {% endwith %}
    </div>
{% endblock body %}

tasks/templates/tasks/years.html
{% extends 'tasks/index.html' %}
{% load tasks_tag %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type='text/css' href="{% static 'tasks/css/month_dates.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'tasks/css/years.css' %}">
{% endblock style %}

{% block body %}
    <div class='dates_container'>
        {% with current_year|add:10 as current_year_plus_10  %}
            {% for year in current_year|add:-10|range:current_year_plus_10 %}
                <a href="{% url 'tasks:url-index-year' year %}"> <div class='dates'> {{ year }} </div> </a>
            {% endfor %}
        {% endwith %}
    </div>
{% endblock body %}